name: lint

on:
  push:
    branches: ["main"]
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-all:
    runs-on: ubuntu-20.04
    steps:
    - run: gh auth setup-git
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1
