name: Release please

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          skip-github-pull-request: true

  release-please-pr:
    runs-on: ubuntu-latest
    needs: release-please-tag
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          skip-github-release: true
